apiVersion: v2
name: tshawytscha-ai-front
description: Frontend for tshawytscha.ai AI platform
type: application
version: 0.1.0
appVersion: "0.0.14"
keywords:
  - ai
  - frontend
  - web
maintainers:
  - name: Alex
